throwErrorOnExtraParameters: true

templates:
  A4 portrait: !template
    reportTemplate: a4_portrait.jrxml
    attributes:
      map: !map
        maxDpi: 254
        width: 555
        height: 800
    processors:
    - !reportBuilder
      directory: '.'
    - !createMap {}
  A4 landscape: !template
    reportTemplate: a4_landscape.jrxml
    attributes:
      map: !map
        maxDpi: 254
        width: 802
        height: 555
    processors:
    - !reportBuilder
      directory: '.'
    - !createMap {}
